import { guideCards, sources } from './data.js';
import { storage } from './store.js';
import { icon, pageHeading, escape, softButton } from './ui.js';

export function renderGuide() {
  const contacts = storage.get().contacts;
  return `${pageHeading('TRAVEL WITH PEACE OF MIND', '把安心，也装进行李。', '给三位大人、两岁宝宝和司机师傅的一份实用提醒。', `<button data-action="settings" class="${softButton}">${icon('contacts-book-line')} 记录联系人</button>`)}
    <section class="mb-6 flex flex-col gap-4 rounded-2xl border border-[#e1e6d5] bg-[#edf1e4] p-6 sm:flex-row sm:items-center"><span class="grid h-14 w-14 shrink-0 place-items-center rounded-2xl bg-[#dfe8cf] text-3xl text-[#73865b]">${icon('shield-check-line')}</span><div class="flex-1"><h2 class="text-lg font-semibold">不逞强、不赶路，有变化就一起调整。</h2><p class="mt-2 text-xs leading-6 text-[#8a947b]">十月北疆注意保暖与山区路况。任何风景都不值得拿安全交换，宝宝的作息和全家人的舒适优先。</p></div><a href="#packing" class="${softButton} shrink-0">检查必备物品 ${icon('arrow-right-line')}</a></section>
    <div class="grid gap-4 md:grid-cols-2 lg:grid-cols-3">${guideCards.map(card => `<article class="flex flex-col rounded-xl border border-[#e4e8dc] bg-white p-5"><div class="mb-5 flex items-center justify-between"><span class="grid h-10 w-10 place-items-center rounded-xl bg-[#f0f3e8] text-xl text-[#829469]">${icon(card.icon)}</span><span class="rounded-full border border-[#edf0e7] px-2.5 py-1 text-[10px] text-[#95a185]">${card.label}</span></div><h2 class="text-sm font-semibold">${card.title}</h2><p class="mb-4 mt-3 text-xs leading-7 text-[#8d9781]">${card.text}</p><p class="mt-auto rounded-lg bg-[#f7f8f1] p-3 text-[11px] leading-6 text-[#929978]">${icon('lightbulb-line', 'mr-1 text-[#b4a66c]')}${card.tip}</p></article>`).join('')}</div>
    <section class="mt-7 rounded-2xl border border-[#e3e7db] bg-white p-6"><div class="mb-5 flex items-center justify-between"><h2 class="flex items-center gap-2 text-base font-semibold">${icon('phone-line', 'text-[#8a9a74]')} 需要时，找得到人</h2><button data-action="settings" class="text-xs text-[#82926b] hover:text-[#365740]">${icon('edit-line')} 编辑联系人</button></div>
      <div class="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">${[{ name: '行程师傅', text: contacts.driver || '暂未填写，出发前记一下', icon: 'steering-2-line' }, { name: '行程管家', text: contacts.steward || '暂未填写，出发前记一下', icon: 'customer-service-2-line' }].map(contact => `<div class="rounded-xl border border-[#e8ecdf] p-4"><span class="text-lg text-[#92a27d]">${icon(contact.icon)}</span><h3 class="mt-2 text-xs font-semibold">${contact.name}</h3><p class="mt-2 break-words text-[11px] leading-5 text-[#959f86]">${escape(contact.text)}</p></div>`).join('')}<a href="tel:120" class="rounded-xl border border-[#e8ecdf] p-4 hover:bg-[#f8f9f3]"><span class="text-lg text-[#a88b74]">${icon('first-aid-kit-line')}</span><h3 class="mt-2 text-xs font-semibold">医疗急救 · 120</h3><p class="mt-2 text-[11px] leading-5 text-[#959f86]">紧急情况及时求助，不等待群内回复</p></a><div class="rounded-xl border border-[#e8ecdf] p-4"><span class="text-lg text-[#92a27d]">${icon('alarm-warning-line')}</span><h3 class="mt-2 text-xs font-semibold">其他应急联系</h3><p class="mt-2 text-[11px] leading-5 text-[#959f86]"><a href="tel:110" class="underline underline-offset-4">报警 110</a> · <a href="tel:122" class="underline underline-offset-4">交通事故 122</a></p></div></div>
      <p class="mt-4 text-[10px] leading-5 text-[#a5ad98]">联系人仅保存在当前浏览器；导出备份会包含这些信息，请仅分享给可信赖的同行人。</p>
    </section>
    <section class="mt-6 rounded-xl border border-dashed border-[#dce2d0] p-5"><h2 class="text-xs font-semibold text-[#71835f]">内容依据与使用说明</h2><p class="mt-2 text-[11px] leading-6 text-[#97a187]">行程依据你提供的 8 日路线图；通用提醒结合两张图片及《注意事项》文档整理。家庭建议是针对三大一小的补充，不替代医生意见、景区政策或旅游合同。未接入实时天气、交通、酒店或票务数据。</p><div class="mt-3 flex flex-wrap gap-2">${sources.map((source, index) => `<button data-action="source" data-source="${index}" class="rounded-md border border-[#e0e5d6] bg-white px-3 py-2 text-[10px] text-[#879773] hover:bg-[#f0f4e7]">${icon('image-line', 'mr-1')} ${source.title}</button>`).join('')}</div><p class="mt-3 text-[10px] leading-5 text-[#a1ab93]">照片来自图片检索中的目的地实景，保留原有署名，仅用作本次私人旅行风景参考；如对外发布，请另行确认图片使用权。</p></section>`;
}
